# Student Data Case Study - Summary

In [1]:
## Libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime
import seaborn as sns

In [105]:
## Import data

In [106]:
df = pd.read_csv(r"E:\analytics\data\studentdata.csv")

In [107]:
df.head()

,rollno,name,dob,gender,course,batch,EXCEL,MATHS,PYTHON,RPGM,STATS,age
0,1,XYZ,1994-01-01,M,BSCDS,2016,87,92,79,42,92,23
1,2,XYZ,1994-01-08,M,BSCDS,2017,96,102,89,77,104,23
2,3,XYZ,1994-01-15,M,BSCDS,2016,87,133,89,61,99,23
3,4,XYZ,1994-01-22,M,BSCDS,2017,90,82,71,67,100,23
4,5,XYZ,1994-01-29,F,BSCDS,2016,63,102,83,51,108,23

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   rollno  100 non-null    int64
 1   name    100 non-null    object
 2   dob     100 non-null    object
 3   gender  100 non-null    object
 4   course  100 non-null    object
 5   batch   100 non-null    int64
 6   EXCEL   100 non-null    int64
 7   MATHS   100 non-null    int64
 8   PYTHON  100 non-null    int64
 9   RPGM    100 non-null    int64
 10  STATS   100 non-null    int64
 11  age     100 non-null    int64
dtypes: int64(8), object(4)
memory usage: 9.5+ KB

In [109]:
df.shape

(100, 12)

In [110]:
# 1 column, 1 stats
print(' Stats Min Marks - ', df['STATS'].min())
print(' Stats Max Marks - ', df['STATS'].max())

 Stats Min Marks -  91
 Stats Max Marks -  135

In [111]:
# mean(), std(), var()
# 2 columns, 1 stats
print(' Std Deviation in Stats and Python Marks - ', df[['STATS','PYTHON']].std())

 Std Deviation in Stats and Python Marks -  STATS      9.504592
PYTHON    10.897131
dtype: float64

In [112]:
# 2 columns, 3 stats
print(' Python and Stats Marks - mean, median, max values')
df[["PYTHON", 'STATS']].apply( { "PYTHON" : ["mean","median","max"],
                                     "STATS" : ["mean","median","max"]  })

 Python and Stats Marks - mean, median, max values

        PYTHON   STATS
mean      75.4  110.81
median    75.5  110.00
max      107.0  135.00

## Group by

In [113]:
df.groupby('gender')

In [114]:
df.groupby('gender').groups

{'F': [4, 13, 15, 25, 27, 28, 38, 39, 59, 60, 71, 80, 85, 89, 91], 'M': [0, 1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 26, 29, 30, 31, 32, 33, 34, 35, 36, 37, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 72, 73, 74, 75, 76, 77, 78, 79, 81, 82, 83, 84, 86, 87, 88, 90, 92, 93, 94, 95, 96, 97, 98, 99]}

In [115]:
df.groupby('gender').get_group('M')
# rows which have Male Gender

,rollno,name,dob,gender,course,batch,EXCEL,MATHS,PYTHON,RPGM,STATS,age
0,1,XYZ,1994-01-01,M,BSCDS,2016,87,92,79,42,92,23
1,2,XYZ,1994-01-08,M,BSCDS,2017,96,102,89,77,104,23
2,3,XYZ,1994-01-15,M,BSCDS,2016,87,133,89,61,99,23
3,4,XYZ,1994-01-22,M,BSCDS,2017,90,82,71,67,100,23
5,6,XYZ,1994-02-05,M,BSCDS,2017,74,127,68,77,116,23
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,XYZ,1995-10-28,M,BTCSDA,2017,97,105,64,87,114,21
96,97,XYZ,1995-11-04,M,BTCSDA,2016,69,127,57,73,127,21
97,98,XYZ,1995-11-11,M,BTCSDA,2017,45,108,77,65,113,21
98,99,XYZ,1995-11-18,M,BTCSDA,2016,73,105,81,74,115,21
99,100,XYZ,1995-11-25,M,BTCSDA,2017,72,105,81,95,113,21

In [116]:
# Groups
numcols1 = ['EXCEL','MATHS','PYTHON','RPGM','STATS','age']
numcols2 = df.select_dtypes(include='number').columns
genderGp = df.groupby('gender')

In [117]:
genderGp[numcols1].sum() #numeric cols

        EXCEL  MATHS  PYTHON  RPGM  STATS   age
gender
F        1144   1560    1174  1018   1642   329
M        6930   8709    6366  5901   9439  1871

In [118]:
genderGp[numcols2].mean() #numeric cols

,rollno,batch,EXCEL,MATHS,PYTHON,RPGM,STATS,age
gender,,,,,,,,
F,49.266667,2016.666667,76.266667,104.000000,78.266667,67.866667,109.466667,21.933333
M,50.717647,2016.470588,81.529412,102.458824,74.894118,69.423529,111.047059,22.011765

In [119]:
genderGp[['EXCEL','age']].aggregate(['mean', 'sum'])

            EXCEL              age
             mean   sum       mean   sum
gender
F       76.266667  1144  21.933333   329
M       81.529412  6930  22.011765  1871

In [120]:
genderGp.aggregate({'EXCEL': 'sum', 'age': 'mean'})

        EXCEL        age
gender
F        1144  21.933333
M        6930  22.011765

In [121]:
print(df.groupby('gender')['STATS'].count())

gender
F    15
M    85
Name: STATS, dtype: int64

In [122]:
df[["PYTHON", 'STATS']].apply( { "PYTHON" : ["mean","median","max"],  "STATS" : ["mean","median","max"]  })

        PYTHON   STATS
mean      75.4  110.81
median    75.5  110.00
max      107.0  135.00

## First N items

In [123]:
# first n items in the group
genderGp.first()   #first row in each group, no order, as per occurance

,rollno,name,dob,course,batch,EXCEL,MATHS,PYTHON,RPGM,STATS,age
gender,,,,,,,,,,,
F,5,XYZ,1994-01-29,BSCDS,2016,63,102,83,51,108,23
M,1,XYZ,1994-01-01,BSCDS,2016,87,92,79,42,92,23

In [124]:
print(df.columns)

Index(['rollno', 'name', 'dob', 'gender', 'course', 'batch', 'EXCEL', 'MATHS',
       'PYTHON', 'RPGM', 'STATS', 'age'],
      dtype='object')

In [125]:
# groupby

In [64]:
df.sort_values('age').groupby('gender').first()

,rollno,name,dob,course,batch,EXCEL,MATHS,PYTHON,RPGM,STATS,age
gender,,,,,,,,,,,
F,81,XYZ,1995-07-15,BTCSDA,2016,84,94,77,55,120,21
M,82,XYZ,1995-07-22,BTCSDA,2017,93,95,82,47,113,21

In [126]:
df1=df.sort_values('gender').groupby('age').first()

In [127]:
df1

,rollno,name,dob,gender,course,batch,EXCEL,MATHS,PYTHON,RPGM,STATS
age,,,,,,,,,,,
21,86,XYZ,1995-08-19,F,BTCSDA,2017,63,78,63,89,106
22,39,XYZ,1994-09-24,F,MSCDS,2016,57,114,82,52,108
23,16,XYZ,1994-04-16,F,BSCDS,2017,70,112,64,87,128

In [128]:
df1=df.sort_values('gender').groupby('age').nth(0)  # To get the full row, including missing values, is to use nth(0)

In [129]:
df1

,rollno,name,dob,gender,course,batch,EXCEL,MATHS,PYTHON,RPGM,STATS,age
15,16,XYZ,1994-04-16,F,BSCDS,2017,70,112,64,87,128,23
85,86,XYZ,1995-08-19,F,BTCSDA,2017,63,78,63,89,106,21
38,39,XYZ,1994-09-24,F,MSCDS,2016,57,114,82,52,108,22

In [130]:
#if you want order to be preserved
#student.groupby(['gender', 'batch'], sort=True).agg({'age': 'mean'})
df.groupby('gender')['age'].rank()
#student[ student.groupby('gender')['age'].rank() == 2 ]

0     75.0
1     75.0
2     75.0
3     75.0
4     14.0
      ...
95    10.5
96    10.5
97    10.5
98    10.5
99    10.5
Name: age, Length: 100, dtype: float64

## Rank

In [131]:
df[ df.groupby('age')['age'].rank(method='average') == 1 ]   # the default

Empty DataFrame
Columns: [rollno, name, dob, gender, course, batch, EXCEL, MATHS, PYTHON, RPGM, STATS, age]
Index: []

In [132]:
df[ df.groupby('age')['gender'].rank(method='min')     == 1 ]

,rollno,name,dob,gender,course,batch,EXCEL,MATHS,PYTHON,RPGM,STATS,age
4,5,XYZ,1994-01-29,F,BSCDS,2016,63,102,83,51,108,23
13,14,XYZ,1994-04-02,F,BSCDS,2017,54,96,82,68,103,23
15,16,XYZ,1994-04-16,F,BSCDS,2017,70,112,64,87,128,23
25,26,XYZ,1994-06-25,F,MSCDS,2017,70,83,80,72,108,22
27,28,XYZ,1994-07-09,F,MSCDS,2017,95,161,86,62,103,22
28,29,XYZ,1994-07-16,F,MSCDS,2016,80,105,86,76,113,22
38,39,XYZ,1994-09-24,F,MSCDS,2016,57,114,82,52,108,22
39,40,XYZ,1994-10-01,F,MSCDS,2017,82,96,92,72,98,22
59,60,XYZ,1995-02-18,F,PGDDS,2017,91,78,75,69,109,22
60,61,XYZ,1995-02-25,F,PGDDS,2016,102,108,64,53,108,22
71,72,XYZ,1995-05-13,F,BTCSDA,2017,80,113,74,74,102,22
80,81,XYZ,1995-07-15,F,BTCSDA,2016,84,94,77,55,120,21
85,86,XYZ,1995-08-19,F,BTCSDA,2017,63,78,63,89,106,21
89,90,XYZ,1995-09-16,F,BTCSDA,2017,68,112,78,70,104,21
91,92,XYZ,1995-09-30,F,BTCSDA,2017,85,108,88,68,124,21

In [71]:
df[ df.groupby('age')['gender'].rank(method='first')   == 1 ]

,rollno,name,dob,gender,course,batch,EXCEL,MATHS,PYTHON,RPGM,STATS,age
4,5,XYZ,1994-01-29,F,BSCDS,2016,63,102,83,51,108,23
25,26,XYZ,1994-06-25,F,MSCDS,2017,70,83,80,72,108,22
80,81,XYZ,1995-07-15,F,BTCSDA,2016,84,94,77,55,120,21

In [133]:
df[ df.groupby('age')['gender'].rank(method='average') == 1 ]   # the default
df[ df.groupby('age')['gender'].rank(method='min')     == 1 ]
df[ df.groupby('age')['gender'].rank(method='first')   == 1 ]

,rollno,name,dob,gender,course,batch,EXCEL,MATHS,PYTHON,RPGM,STATS,age
4,5,XYZ,1994-01-29,F,BSCDS,2016,63,102,83,51,108,23
25,26,XYZ,1994-06-25,F,MSCDS,2017,70,83,80,72,108,22
80,81,XYZ,1995-07-15,F,BTCSDA,2016,84,94,77,55,120,21

## Duplicates

In [134]:
df2=df.drop_duplicates(subset='age')
df2

,rollno,name,dob,gender,course,batch,EXCEL,MATHS,PYTHON,RPGM,STATS,age
0,1,XYZ,1994-01-01,M,BSCDS,2016,87,92,79,42,92,23
24,25,XYZ,1994-06-18,M,MSCDS,2016,111,128,75,60,131,22
76,77,XYZ,1995-06-17,M,BTCSDA,2016,96,158,72,89,104,21

In [135]:
print(df2.shape)

(3, 12)

## Sort

In [140]:
df3=df.sort_values(by='rollno')  # Sort by a column

In [141]:
print(df3)

    rollno name         dob gender  course  batch  EXCEL  MATHS  PYTHON  RPGM  \
0        1  XYZ  1994-01-01      M   BSCDS   2016     87     92      79    42
1        2  XYZ  1994-01-08      M   BSCDS   2017     96    102      89    77
2        3  XYZ  1994-01-15      M   BSCDS   2016     87    133      89    61
3        4  XYZ  1994-01-22      M   BSCDS   2017     90     82      71    67
4        5  XYZ  1994-01-29      F   BSCDS   2016     63    102      83    51
..     ...  ...         ...    ...     ...    ...    ...    ...     ...   ...
95      96  XYZ  1995-10-28      M  BTCSDA   2017     97    105      64    87
96      97  XYZ  1995-11-04      M  BTCSDA   2016     69    127      57    73
97      98  XYZ  1995-11-11      M  BTCSDA   2017     45    108      77    65
98      99  XYZ  1995-11-18      M  BTCSDA   2016     73    105      81    74
99     100  XYZ  1995-11-25      M  BTCSDA   2017     72    105      81    95

    STATS  age
0      92   23
1     104   23
2      99   23
3     100   23
4     108   23
..    ...  ...
95    114   21
96    127   21
97    113   21
98    115   21
99    113   21

[100 rows x 12 columns]

In [142]:
df.sort_values(by='rollno', ascending=False) # Sort in descending order

,rollno,name,dob,gender,course,batch,EXCEL,MATHS,PYTHON,RPGM,STATS,age
99,100,XYZ,1995-11-25,M,BTCSDA,2017,72,105,81,95,113,21
98,99,XYZ,1995-11-18,M,BTCSDA,2016,73,105,81,74,115,21
97,98,XYZ,1995-11-11,M,BTCSDA,2017,45,108,77,65,113,21
96,97,XYZ,1995-11-04,M,BTCSDA,2016,69,127,57,73,127,21
95,96,XYZ,1995-10-28,M,BTCSDA,2017,97,105,64,87,114,21
...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,XYZ,1994-01-29,F,BSCDS,2016,63,102,83,51,108,23
3,4,XYZ,1994-01-22,M,BSCDS,2017,90,82,71,67,100,23
2,3,XYZ,1994-01-15,M,BSCDS,2016,87,133,89,61,99,23
1,2,XYZ,1994-01-08,M,BSCDS,2017,96,102,89,77,104,23
0,1,XYZ,1994-01-01,M,BSCDS,2016,87,92,79,42,92,23

In [143]:
print(df3)

    rollno name         dob gender  course  batch  EXCEL  MATHS  PYTHON  RPGM  \
0        1  XYZ  1994-01-01      M   BSCDS   2016     87     92      79    42
1        2  XYZ  1994-01-08      M   BSCDS   2017     96    102      89    77
2        3  XYZ  1994-01-15      M   BSCDS   2016     87    133      89    61
3        4  XYZ  1994-01-22      M   BSCDS   2017     90     82      71    67
4        5  XYZ  1994-01-29      F   BSCDS   2016     63    102      83    51
..     ...  ...         ...    ...     ...    ...    ...    ...     ...   ...
95      96  XYZ  1995-10-28      M  BTCSDA   2017     97    105      64    87
96      97  XYZ  1995-11-04      M  BTCSDA   2016     69    127      57    73
97      98  XYZ  1995-11-11      M  BTCSDA   2017     45    108      77    65
98      99  XYZ  1995-11-18      M  BTCSDA   2016     73    105      81    74
99     100  XYZ  1995-11-25      M  BTCSDA   2017     72    105      81    95

    STATS  age
0      92   23
1     104   23
2      99   23
3     100   23
4     108   23
..    ...  ...
95    114   21
96    127   21
97    113   21
98    115   21
99    113   21

[100 rows x 12 columns]

In [144]:
df.sort_values(by=['course', 'rollno']) # Sort by multiple columns

,rollno,name,dob,gender,course,batch,EXCEL,MATHS,PYTHON,RPGM,STATS,age
0,1,XYZ,1994-01-01,M,BSCDS,2016,87,92,79,42,92,23
1,2,XYZ,1994-01-08,M,BSCDS,2017,96,102,89,77,104,23
2,3,XYZ,1994-01-15,M,BSCDS,2016,87,133,89,61,99,23
3,4,XYZ,1994-01-22,M,BSCDS,2017,90,82,71,67,100,23
4,5,XYZ,1994-01-29,F,BSCDS,2016,63,102,83,51,108,23
...,...,...,...,...,...,...,...,...,...,...,...,...
60,61,XYZ,1995-02-25,F,PGDDS,2016,102,108,64,53,108,22
61,62,XYZ,1995-03-04,M,PGDDS,2017,87,92,67,67,104,22
62,63,XYZ,1995-03-11,M,PGDDS,2016,74,130,75,62,99,22
63,64,XYZ,1995-03-18,M,PGDDS,2017,79,68,85,44,118,22
64,65,XYZ,1995-03-25,M,PGDDS,2016,73,92,71,67,110,22

In [145]:
print(df3)

    rollno name         dob gender  course  batch  EXCEL  MATHS  PYTHON  RPGM  \
0        1  XYZ  1994-01-01      M   BSCDS   2016     87     92      79    42
1        2  XYZ  1994-01-08      M   BSCDS   2017     96    102      89    77
2        3  XYZ  1994-01-15      M   BSCDS   2016     87    133      89    61
3        4  XYZ  1994-01-22      M   BSCDS   2017     90     82      71    67
4        5  XYZ  1994-01-29      F   BSCDS   2016     63    102      83    51
..     ...  ...         ...    ...     ...    ...    ...    ...     ...   ...
95      96  XYZ  1995-10-28      M  BTCSDA   2017     97    105      64    87
96      97  XYZ  1995-11-04      M  BTCSDA   2016     69    127      57    73
97      98  XYZ  1995-11-11      M  BTCSDA   2017     45    108      77    65
98      99  XYZ  1995-11-18      M  BTCSDA   2016     73    105      81    74
99     100  XYZ  1995-11-25      M  BTCSDA   2017     72    105      81    95

    STATS  age
0      92   23
1     104   23
2      99   23
3     100   23
4     108   23
..    ...  ...
95    114   21
96    127   21
97    113   21
98    115   21
99    113   21

[100 rows x 12 columns]

In [148]:
df3=df.sort_index # Sort by index

In [149]:
print(df3)

<bound method DataFrame.sort_index of     rollno name         dob gender  course  batch  EXCEL  MATHS  PYTHON  RPGM  \
0        1  XYZ  1994-01-01      M   BSCDS   2016     87     92      79    42
1        2  XYZ  1994-01-08      M   BSCDS   2017     96    102      89    77
2        3  XYZ  1994-01-15      M   BSCDS   2016     87    133      89    61
3        4  XYZ  1994-01-22      M   BSCDS   2017     90     82      71    67
4        5  XYZ  1994-01-29      F   BSCDS   2016     63    102      83    51
..     ...  ...         ...    ...     ...    ...    ...    ...     ...   ...
95      96  XYZ  1995-10-28      M  BTCSDA   2017     97    105      64    87
96      97  XYZ  1995-11-04      M  BTCSDA   2016     69    127      57    73
97      98  XYZ  1995-11-11      M  BTCSDA   2017     45    108      77    65
98      99  XYZ  1995-11-18      M  BTCSDA   2016     73    105      81    74
99     100  XYZ  1995-11-25      M  BTCSDA   2017     72    105      81    95

    STATS  age
0      92   23
1     104   23
2      99   23
3     100   23
4     108   23
..    ...  ...
95    114   21
96    127   21
97    113   21
98    115   21
99    113   21

[100 rows x 12 columns]>